import { createServerFn } from "@tanstack/react-start";
import { createClient } from "@supabase/supabase-js";
import { z } from "zod";
import type { Database } from "@/integrations/supabase/types";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { notifyBoth, OWNER_EMAIL } from "./notify.server";
import { assertAdmin, logAudit } from "./admin/audit.server";

const ItemSchema = z.object({
  product_id: z.string().uuid(),
  name: z.string(),
  price: z.coerce.number().nonnegative(),
  qty: z.coerce.number().int().min(1),
});

const OrderInput = z.object({
  customer_name: z.string().trim().min(2),
  customer_email: z.string().trim().email(),
  customer_phone: z.string().trim().min(7),
  fulfillment: z.enum(["delivery", "pickup"]),
  delivery_address: z.string().optional().default(""),
  notes: z.string().optional().default(""),
  delivery_lat: z.number().finite().nullable().optional(),
  delivery_lng: z.number().finite().nullable().optional(),
  delivery_note: z.string().max(500).optional().default(""),
  items: z.array(ItemSchema).min(1),
});

function gen(prefix: string, n: number) {
  const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let out = prefix;
  for (let i = 0; i < n; i++) out += alphabet[Math.floor(Math.random() * alphabet.length)];
  return out;
}

export const placeOrder = createServerFn({ method: "POST" })
  .inputValidator((data: z.infer<typeof OrderInput>) => OrderInput.parse(data))
  .handler(async ({ data }) => {
    const supabase = createClient<Database>(
      process.env.SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
      { auth: { persistSession: false, autoRefreshToken: false } },
    );
    const subtotal = data.items.reduce((s, it) => s + it.price * it.qty, 0);
    const total = subtotal; // no tax/shipping for v1
    const isPickup = data.fulfillment === "pickup";
    const reservation_number = isPickup ? `FCS-${gen("", 6)}` : null;
    const pickup_code = isPickup ? gen("", 4) : null;

    // Anonymous checkout is supported; signed-in customers can later view
    // these orders via the email-match RLS policy on `orders`.
    const userId: string | null = null;

    const { data: order, error } = await supabase
      .from("orders")
      .insert({
        user_id: userId,
        customer_name: data.customer_name,
        customer_email: data.customer_email,
        customer_phone: data.customer_phone,
        fulfillment: data.fulfillment,
        delivery_address: data.delivery_address ?? "",
        delivery_lat: data.delivery_lat ?? null,
        delivery_lng: data.delivery_lng ?? null,
        delivery_note: data.delivery_note ?? "",
        items: data.items as never,
        subtotal,
        total,
        notes: data.notes ?? "",
        status: "pending",
        payment_status: "unpaid",
        reservation_number,
        pickup_code,
      })
      .select("id, reservation_number, pickup_code, invoice_number")
      .single();
    if (error) throw new Error(error.message);
    // Backfill invoice number if not generated by default
    let invoice_number = order.invoice_number;
    if (!invoice_number) {
      invoice_number = `INV-${order.id.replace(/-/g, "").slice(0, 10).toUpperCase()}`;
      await supabase.from("orders").update({ invoice_number }).eq("id", order.id);
    }

    // Decrement stock
    for (const it of data.items) {
      const { data: prod } = await supabase.from("products").select("stock").eq("id", it.product_id).single();
      const newStock = Math.max(0, (prod?.stock ?? 0) - it.qty);
      await supabase.from("products").update({ stock: newStock }).eq("id", it.product_id);
      await supabase.from("inventory_movements").insert({
        product_id: it.product_id, delta: -it.qty, reason: "order", reference_id: order.id, admin_id: null,
      });
    }

    // Email + notification trail
    const summary = data.items.map((it) => `• ${it.name} × ${it.qty}`).join("\n");
    await notifyBoth(supabase, {
      customerEmail: data.customer_email,
      customerUserId: userId,
      kind: "order-placed",
      adminSubject: `New order ${invoice_number} — KES ${total.toLocaleString()}`,
      adminBody: `New order from ${data.customer_name} (${data.customer_email}, ${data.customer_phone}).\nFulfillment: ${data.fulfillment}${isPickup ? ` (Reservation ${reservation_number}, code ${pickup_code})` : ""}\n\n${summary}\n\nTotal: KES ${total.toLocaleString()}`,
      customerSubject: `We received your order ${invoice_number}`,
      customerBody: `Hi ${data.customer_name},\n\nThanks for your order with Favour Computer Services.\nYour reference is ${invoice_number}.\n\n${summary}\n\nTotal: KES ${total.toLocaleString()}\n\nNext step: upload your proof of payment from your account so we can verify and prepare your order.\n\nFavour Computer Services\n0726 548 592 — F&F Building, Shop U13, Nairobi`,
      relatedType: "order",
      relatedId: order.id,
    });

    return { ...order, invoice_number };
  });

// ───────────────────────── Customer account ─────────────────────────

export const listMyOrders = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const email = (context.claims?.email as string | undefined) ?? "";
    const { data, error } = await context.supabase
      .from("orders")
      .select("id, invoice_number, created_at, total, status, payment_status, fulfillment, reservation_number, pickup_code, items, customer_email")
      .or(`user_id.eq.${context.userId}${email ? `,customer_email.ilike.${email}` : ""}`)
      .order("created_at", { ascending: false })
      .limit(200);
    if (error) throw new Error(error.message);
    return data ?? [];
  });

export const getMyOrder = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: { id: string }) => z.object({ id: z.string().uuid() }).parse(d))
  .handler(async ({ data, context }) => {
    const { data: order, error } = await context.supabase
      .from("orders")
      .select("*")
      .eq("id", data.id)
      .maybeSingle();
    if (error) throw new Error(error.message);
    if (!order) throw new Error("Order not found");
    const { data: payments } = await context.supabase
      .from("payments")
      .select("*")
      .eq("order_id", data.id)
      .order("created_at", { ascending: false });
    const { data: notifications } = await context.supabase
      .from("notifications")
      .select("kind, subject, body, created_at")
      .eq("related_id", data.id)
      .order("created_at", { ascending: false });
    const productIds = Array.from(
      new Set(
        (Array.isArray((order as { items?: unknown }).items)
          ? ((order as { items: Array<{ product_id?: string }> }).items)
          : []
        ).map((i) => i?.product_id).filter((v): v is string => typeof v === "string")
      )
    );
    let products: Array<Record<string, unknown>> = [];
    if (productIds.length) {
      const { data: prods } = await context.supabase
        .from("products")
        .select("id, name, processor, ram, storage, warranty, condition, specs")
        .in("id", productIds);
      products = (prods ?? []) as never;
    }
    return { order, payments: payments ?? [], notifications: notifications ?? [], products };
  });

// ───────────────────────── Admin ─────────────────────────

const UpdateOrderInput = z.object({
  id: z.string().uuid(),
  status: z.enum(["pending","paid","ready","picked_up","delivered","cancelled"]).optional(),
  payment_status: z.enum(["unpaid","awaiting_verification","paid","refunded"]).optional(),
  notes: z.string().max(5000).optional(),
});

export const adminUpdateOrder = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: z.infer<typeof UpdateOrderInput>) => UpdateOrderInput.parse(d))
  .handler(async ({ data, context }) => {
    await assertAdmin(context.supabase, context.userId);
    const { id, ...patch } = data;
    const { data: updated, error } = await context.supabase
      .from("orders").update(patch as never).eq("id", id).select("customer_email, customer_name, invoice_number, user_id").single();
    if (error) throw new Error(error.message);
    await logAudit(context.supabase, {
      adminId: context.userId, adminEmail: context.claims?.email ?? "",
      action: "update", entity: "order", entityId: id, details: patch,
    });
    // Notify customer about meaningful status flips
    const kinds: Record<string, { subj: string; body: string }> = {
      ready: { subj: `Your order ${updated.invoice_number} is ready for pickup`, body: `Hi ${updated.customer_name},\n\nYour order ${updated.invoice_number} is ready for pickup at F&F Building, Shop U13, Nairobi.` },
      delivered: { subj: `Your order ${updated.invoice_number} was delivered`, body: `Hi ${updated.customer_name},\n\nWe've marked order ${updated.invoice_number} as delivered. Enjoy!` },
      picked_up: { subj: `Order ${updated.invoice_number} picked up`, body: `Hi ${updated.customer_name},\n\nThanks for collecting order ${updated.invoice_number} at our shop.` },
      cancelled: { subj: `Order ${updated.invoice_number} cancelled`, body: `Hi ${updated.customer_name},\n\nYour order ${updated.invoice_number} has been cancelled.` },
    };
    if (patch.status && kinds[patch.status]) {
      const k = kinds[patch.status];
      await notifyBoth(context.supabase, {
        customerEmail: updated.customer_email, customerUserId: updated.user_id,
        kind: `order-${patch.status}`,
        adminSubject: `Order ${updated.invoice_number} → ${patch.status}`,
        adminBody: `Status changed by admin to ${patch.status}.`,
        customerSubject: k.subj, customerBody: k.body,
        relatedType: "order", relatedId: id,
      });
    }
    return { ok: true };
  });

export const adminListOrders = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    await assertAdmin(context.supabase, context.userId);
    const { data, error } = await context.supabase.from("orders").select("*").order("created_at", { ascending: false }).limit(500);
    if (error) throw new Error(error.message);
    return data ?? [];
  });

export { OWNER_EMAIL };